version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout

      - run: |
            chmod +x ./detectGitChanges.sh
            chmod +x ./src/run.sh 
            FLG=$(./detectGitChanges.sh folders.watch)
            echo "$FLG"
            if [[  $FLG == *"true"*  ]]; then
              ./src/run.sh
            else
              echo "No changes"
            fi

