version: 2.1
orbs:
    swissknife: roopakv/swissknife@0.37.0


jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    steps:
      - checkout

      - run: |
            chmod +x ./detectGitChanges.sh
            chmod +x ./src/run.sh 
            FLG=$(./detectGitChanges.sh folders.watch)
            echo "$FLG"
            if [[  $FLG == *"true"*  ]]; then
              ./src/run.sh
            else
              echo "No changes"
            fi
      - swissknife/run_if_modified:
          pattern: src
          steps-to-run:
            - run:
                command: |
                  echo "src was modified";
                  chmod +x ./src/run.sh && ./src/run.sh;
                  exit 0;